// Generated by dts-bundle v0.7.3

declare module '@utkusarioglu/event-emitter' {
    export { EventEmitter } from "@utkusarioglu/event-emitter/event-emitter";
}

declare module '@utkusarioglu/event-emitter/event-emitter' {
    export class EventEmitter {
        on(event_name: string, callback: (transmission: any) => void): void;
        once(event_name: string, callback: (transmission: any) => void): void;
        emit(event_name: string, transmission: any): void;
        setMaxListeners(max_listener_count: number): this;
        eventNames(): string[];
    }
}

